### ISSUE TITLE
Dots not in the code

### ISSUE THREAD

**Issue by LouisCAD** [googlecodelabs/android-agera#5]
Hi!

I spotted formatting issues in the codelab!

[On this page](https://codelabs.developers.google.com/codelabs/android-agera/index.html?index=..%2F..%2Findex#7) (maybe other pages too), you can notice multiple places where it's written this:

call .`nameOfTheAwesomeMethod()`

instead of this:

call `.nameOfTheAwesomeMethod()`

The dot is misplaced, and may mislead readers, thinking it's the end of the sentence, while it's a method call dot.

**Comment by JoseAlcerreca** [comment]
Fixed! https://codelabs.developers.google.com/codelabs/android-agera/index.html?index=..%2F..%2Findex#7
