### ISSUE TITLE
doc: attemptOperation vs. performOperation

### ISSUE THREAD

**Issue by tmtron** [googlecodelabs/android-agera#7]
In the code-examples of [Step 10](https://codelabs.developers.google.com/codelabs/android-agera/index.html?index=..%2F..%2Findex#9) and [Step 11](https://codelabs.developers.google.com/codelabs/android-agera/index.html?index=..%2F..%2Findex#10) of the code-lab 

> CalculatorOperations::attemptOperation

must be used instead of

> CalculatorUtils::performOperation

**Comment by JoseAlcerreca** [comment]
Fixed, thanks!
https://codelabs.developers.google.com/codelabs/android-agera/index.html?index=..%2F..%2Findex#9
