### ISSUE TITLE
Step 6) myDataSupplier and mStringRepo field clash

### ISSUE THREAD

**Issue by tomaszrykala** [googlecodelabs/android-agera#8]
When following step 6, the `MyDataSupplier` instance is still called `myDataSupplier` so this one should be called in the refactored lambda expression.

`updatable = () -> Log.d("AGERA", mStringRepo.get());`
should be
`updatable = () -> Log.d("AGERA", myDataSupplier.get());`

**Comment by JoseAlcerreca** [comment]
Fixed in https://codelabs.developers.google.com/codelabs/android-agera/index.html?index=..%2F..%2Findex#5

thanks!
