### ISSUE TITLE
Slide 6 (Step 1: Hello world)

### ISSUE THREAD

**Issue by bmax-moblin** [googlecodelabs/android-agera#9]
The Repository block in the image (https://codelabs.developers.google.com/codelabs/android-agera/img/3ea52d24131744e6.png) contains three elements (Receiver, Observer, Supplier). It seems, that they correspond with the interfaces implemented by MyDataSupplier. Shouldn't the second element be Observable instead of Observer?

**Comment by JoseAlcerreca** [comment]
Yep, fixing now.

**Comment by JoseAlcerreca** [comment]
Fixed, thanks
https://codelabs.developers.google.com/codelabs/android-agera/index.html?index=..%2F..%2Findex#5
